version: '2'
services:
  web:
    # env_file: .env
    build:
      context: . 
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/_build
    command: mix phoenix.server